export const SAFETY_STATUS = {
  SAFE: 'SAFE',
  WARNING: 'WARNING',
  EMERGENCY: 'EMERGENCY',
  OFFLINE: 'OFFLINE',
};

export const VIHAR_STATUS = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const ROUTE_EVENT_TYPES = {
  DEVIATION_LEVEL_1: 'DEVIATION_LEVEL_1',
  DEVIATION_LEVEL_2: 'DEVIATION_LEVEL_2',
  STATIONARY_ALERT: 'STATIONARY_ALERT',
  LOW_BATTERY: 'LOW_BATTERY',
  CRITICAL_BATTERY: 'CRITICAL_BATTERY',
  NETWORK_LOST: 'NETWORK_LOST',
  NETWORK_RESTORED: 'NETWORK_RESTORED',
  ROUTE_RECOVERED: 'ROUTE_RECOVERED',
};
